// <auto-generated />
namespace TeamSports.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userid_to_owner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userid_to_owner));
        
        string IMigrationMetadata.Id
        {
            get { return "201608041545099_userid_to_owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
