// <auto-generated />
namespace TeamSports.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usersevents_clear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usersevents_clear));
        
        string IMigrationMetadata.Id
        {
            get { return "201608040712482_usersevents_clear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
