// <auto-generated />
namespace TeamSports.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class city_geolocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(city_geolocations));
        
        string IMigrationMetadata.Id
        {
            get { return "201608081656171_city_geolocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
