// <auto-generated />
namespace TeamSports.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_list_to_collections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_list_to_collections));
        
        string IMigrationMetadata.Id
        {
            get { return "201608032023259_change_list_to_collections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
